### ISSUE TITLE
action not found

### ISSUE THREAD

**Issue by hannesa2** [ravinderjangra/android-ndk-toolchain-setup#1]
I tried your action with

name: CI Android

```
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: NDK
        uses: actions/android-ndk-toolchain-setup@v0.1
        with:
          api: '21'
          arch: 'x86'
          install-location: 'toolchains'
          force: true
      - name: Build with Gradle
        run: ./gradlew build
```

But I run into https://github.com/marianmoldovan/panoramagl/runs/477801639

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3314607/75625189-f5daf180-5bbb-11ea-81d6-03ba8a16caaa.png">

Do you have any clue, what I did wrong ?

**Comment by ravinderjangra** [comment]
Hey @hannesa2, I think I know what may be the reason. It seems I didn't update the docs correctly.

Could you please try updating:
` uses: actions/android-ndk-toolchain-setup@v0.1`
to
` uses: ravinderjangra/android-ndk-toolchain-setup@v0.1`

**Comment by hannesa2** [comment]
I followed you suggestion https://github.com/marianmoldovan/panoramagl/commit/212fbdf1d13a43d330350be53ec72e66693c4dc4 but still run into a 404 error https://github.com/marianmoldovan/panoramagl/runs/478878116

**Comment by ravinderjangra** [comment]
I'll just try this and see if this works fine.

**Comment by ravinderjangra** [comment]
I just tried creating a new GHA workflow and this works fine.
CI: https://github.com/ravinderjangra/AndroidResumeIssue/runs/478893210
workflow: https://github.com/ravinderjangra/AndroidResumeIssue/blob/master/.github/workflows/main.yml

The only thing I'm doing differently is creating a `toolchains` folder which we are passing as `install-location`. The action doesn't automatically create that folder so I'm creating the before calling this action.

**Comment by hannesa2** [comment]
Yes !
[This](https://github.com/marianmoldovan/panoramagl/pull/17/commits/95a0ed8e2d93805b66a68725704efcd8deee6af8) solves the issue.

Thank you

**Comment by hannesa2** [comment]
> Could you please try updating:
> ` uses: actions/android-ndk-toolchain-setup@v0.1`
> to
> ` uses: ravinderjangra/android-ndk-toolchain-setup@v0.1`

Just for the records, to avoid confusion other people

That's wrong
 `uses: ravinderjangra/android-ndk-toolchain-setup@v0.1`

That's right
 `uses: ravinderjangra/android-ndk-toolchain-setup@0.1`

**Comment by hannesa2** [comment]
Now I run into 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3314607/79536094-788e1200-807f-11ea-8eda-c9362da95ebf.png">

and I use your recommendation 
```
      - shell: bash
        run: mkdir toolchains
      - name: specify NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.1
        with:
          api: '21'
          arch: 'x86'
          install-location: 'toolchains'
          force: true
```

But maybe it's related to runs-on: you use
    `runs-on: ubuntu-latest`
and I use 
   `runs-on: macOS-latest`
